//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmobiliaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class COBROS_DETALLES
    {
        public long COBRO_DETALLE_ID { get; set; }
        public long COBRO_ID { get; set; }
        public Nullable<int> NUMERO_ITEM { get; set; }
        public decimal MONTO_DOCUMENTO { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public long MONEDA_DOCUMENTO { get; set; }
        public decimal MONTO_PAGADO { get; set; }
        public long MONEDA_PAGO { get; set; }
        public long FORMA_PAGO_ID { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string OBSERVACION { get; set; }
        public decimal TASA_CAMBIO { get; set; }
        public Nullable<long> DOCUMENTO_ID { get; set; }
    }
}
