//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmobiliaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRONOGRAMAS_CUOTAS_VIEW
    {
        public long CRONOGRAMA_CUOTA_ID { get; set; }
        public Nullable<int> NUMERO_CUOTA { get; set; }
        public Nullable<System.DateTime> FECHA_VENCIMIENTO { get; set; }
        public decimal MONTO { get; set; }
        public long OPERACION_PROPIEDAD_ID { get; set; }
        public string TIPO_OPERACION { get; set; }
        public long SOCIO_NEGOCIO_ID { get; set; }
        public string SOCIO_NEGOCIO { get; set; }
        public string ESTADO { get; set; }
        public long MONEDA_ID { get; set; }
        public string MONEDA { get; set; }
        public Nullable<System.DateTime> FECHA_CANCELACION { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public long ENTIDAD_INMOBILIARIA_ID { get; set; }
        public string ENTIDAD { get; set; }
        public long PROPIEDAD_ID { get; set; }
        public string PROPIEDAD { get; set; }
    }
}
