//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmobiliaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTAMENTOS_PAISES_VIEW
    {
        public long DEPARTAMENTO_PAIS_ID { get; set; }
        public long PAIS_ID { get; set; }
        public string PAIS { get; set; }
        public string NACIONALIDAD { get; set; }
        public string CODIGO_ISO2 { get; set; }
        public string CODIGO_ISO3 { get; set; }
        public long DEPARTAMENTO_ID { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string CODIGO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
