//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmobiliaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESAS
    {
        public EMPRESAS()
        {
            this.ENTIDADES_INMOBILIARIAS = new HashSet<ENTIDADES_INMOBILIARIAS>();
            this.PROPIEDADES = new HashSet<PROPIEDADES>();
            this.SUCURSALES = new HashSet<SUCURSALES>();
            this.USUARIOS = new HashSet<USUARIOS>();
        }
    
        public long EMPRESA_ID { get; set; }
        public Nullable<long> SOCIO_NEGOCIO_ID { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public string NOMBRE_CORTO { get; set; }
        public string NUMERO_DOCUMENTO { get; set; }
        public string DIGITO_VERIFICADOR { get; set; }
        public string TIPO_PERSONERIA { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string ACTIVO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    
        public virtual SOCIOS_NEGOCIOS SOCIOS_NEGOCIOS { get; set; }
        public virtual ICollection<ENTIDADES_INMOBILIARIAS> ENTIDADES_INMOBILIARIAS { get; set; }
        public virtual ICollection<PROPIEDADES> PROPIEDADES { get; set; }
        public virtual ICollection<SUCURSALES> SUCURSALES { get; set; }
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
    }
}
