//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmobiliaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTIDADES_INMOBILIARIAS
    {
        public ENTIDADES_INMOBILIARIAS()
        {
            this.PROPIEDADES = new HashSet<PROPIEDADES>();
        }
    
        public long ENTIDAD_INMOBILIARIA_ID { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<long> EMPRESA_ID { get; set; }
        public Nullable<long> PAIS_ID { get; set; }
        public Nullable<long> DEPARTAMENTO_ID { get; set; }
        public Nullable<long> CIUDAD_ID { get; set; }
        public Nullable<long> BARRIO_ID { get; set; }
        public string TIPO { get; set; }
        public string CUENTA_CATASTRAL { get; set; }
        public Nullable<int> CANTIDAD_UNIDADES { get; set; }
        public Nullable<int> ANO_CONSTRUCCION { get; set; }
        public Nullable<int> M2_CONSTRUCCION { get; set; }
        public string MEDIDAS_LOTE { get; set; }
        public string NUMERO_FINCA { get; set; }
        public string CARACTERISTICA { get; set; }
        public string NATURALEZA { get; set; }
        public string DIRECCION { get; set; }
        public string ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string OBSERVACION { get; set; }
    
        public virtual BARRIOS BARRIOS { get; set; }
        public virtual CIUDADES CIUDADES { get; set; }
        public virtual DEPARTAMENTOS DEPARTAMENTOS { get; set; }
        public virtual EMPRESAS EMPRESAS { get; set; }
        public virtual PAISES PAISES { get; set; }
        public virtual ICollection<PROPIEDADES> PROPIEDADES { get; set; }
    }
}
