//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmobiliaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class IBE_VERSION_HISTORY
    {
        public int IBE_VH_ID { get; set; }
        public System.DateTime IBE_VH_MODIFY_DATE { get; set; }
        public string IBE_VH_USER_NAME { get; set; }
        public short IBE_VH_OBJECT_TYPE { get; set; }
        public string IBE_VH_OBJECT_NAME { get; set; }
        public byte[] IBE_VH_HEADER { get; set; }
        public byte[] IBE_VH_BODY { get; set; }
        public string IBE_VH_DESCRIPTION { get; set; }
    }
}
