//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmobiliaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGENES_OPERACIONES_VIEW
    {
        public long IMAGEN_OPERACION_ID { get; set; }
        public byte[] IMAGEN { get; set; }
        public long OPERACION_ID { get; set; }
        public System.DateTime FECHA_OPERACION { get; set; }
        public string TIPO_OPERACION { get; set; }
        public string SOCIO_NEGOCIO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
