//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmobiliaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGRESOS_EGRESOS_VIEW
    {
        public long INGRESO_EGRESO_ID { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal MONTO { get; set; }
        public Nullable<long> SOCIO_NEGOCIO_ID { get; set; }
        public string SOCIO_NEGOCIO { get; set; }
        public string ESTADO { get; set; }
        public Nullable<long> ENTIDAD_INMOBILIARIA_ID { get; set; }
        public string ENTIDAD_INMOBILIARIA { get; set; }
        public string TIPO { get; set; }
        public Nullable<long> PROPIEDAD_ID { get; set; }
        public string PROPIEDAD { get; set; }
        public long ITEM_INGRESO_EGRESO_ID { get; set; }
        public string ITEM { get; set; }
        public string NUMERO_FACTURA { get; set; }
        public Nullable<System.DateTime> FECHA_FACTURA { get; set; }
        public decimal SALDO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string TIPO_IMPUTACION { get; set; }
    }
}
