//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmobiliaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMS_INGRESOS_EGRESOS
    {
        public long ITEM_INGRESO_EGRESO_ID { get; set; }
        public string ITEM { get; set; }
        public string TIPO_ITEM { get; set; }
        public string TIPO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string MODIFICA_ESTADO { get; set; }
        public string APLICACION { get; set; }
    }
}
