//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmobiliaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIQUIDACIONES_DETALLES
    {
        public long LIQUIDACION_DETALLE_ID { get; set; }
        public long LIQUIDACION_ID { get; set; }
        public Nullable<int> NUMERO_ITEM { get; set; }
        public long ITEM_INGRESO_EGRESO_ID { get; set; }
        public decimal MONTO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
