//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmobiliaria.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InmobiliariaEntities : DbContext
    {
        public InmobiliariaEntities()
            : base("name=InmobiliariaEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BARRIOS> BARRIOS { get; set; }
        public DbSet<BARRIOS_CIUDADES> BARRIOS_CIUDADES { get; set; }
        public DbSet<CIUDADES> CIUDADES { get; set; }
        public DbSet<CIUDADES_DEPARTAMENTOS> CIUDADES_DEPARTAMENTOS { get; set; }
        public DbSet<COBROS> COBROS { get; set; }
        public DbSet<COBROS_DETALLES> COBROS_DETALLES { get; set; }
        public DbSet<CRONOGRAMAS_CUOTAS> CRONOGRAMAS_CUOTAS { get; set; }
        public DbSet<DEPARTAMENTOS> DEPARTAMENTOS { get; set; }
        public DbSet<DEPARTAMENTOS_PAISES> DEPARTAMENTOS_PAISES { get; set; }
        public DbSet<DOMINIOS> DOMINIOS { get; set; }
        public DbSet<EMPRESAS> EMPRESAS { get; set; }
        public DbSet<ENTIDADES_INMOBILIARIAS> ENTIDADES_INMOBILIARIAS { get; set; }
        public DbSet<FORMAS_PAGOS> FORMAS_PAGOS { get; set; }
        public DbSet<IBE_VERSION_HISTORY> IBE_VERSION_HISTORY { get; set; }
        public DbSet<IMAGENES_ENTIDAD_INMOBILIARIA> IMAGENES_ENTIDAD_INMOBILIARIA { get; set; }
        public DbSet<IMAGENES_OPERACIONES> IMAGENES_OPERACIONES { get; set; }
        public DbSet<IMPUESTOS> IMPUESTOS { get; set; }
        public DbSet<INGRESOS_EGRESOS> INGRESOS_EGRESOS { get; set; }
        public DbSet<ITEMS_INGRESOS_EGRESOS> ITEMS_INGRESOS_EGRESOS { get; set; }
        public DbSet<LIQUIDACIONES> LIQUIDACIONES { get; set; }
        public DbSet<LIQUIDACIONES_DETALLES> LIQUIDACIONES_DETALLES { get; set; }
        public DbSet<MONEDAS> MONEDAS { get; set; }
        public DbSet<OPERACIONES_PROPIEDADES> OPERACIONES_PROPIEDADES { get; set; }
        public DbSet<PAISES> PAISES { get; set; }
        public DbSet<PROPIEDADES> PROPIEDADES { get; set; }
        public DbSet<PROPIETARIOS_ENT_INMOB> PROPIETARIOS_ENT_INMOB { get; set; }
        public DbSet<RESCISIONES> RESCISIONES { get; set; }
        public DbSet<RUC> RUC { get; set; }
        public DbSet<SOCIOS_NEGOCIOS> SOCIOS_NEGOCIOS { get; set; }
        public DbSet<SUCURSALES> SUCURSALES { get; set; }
        public DbSet<USUARIOS> USUARIOS { get; set; }
        public DbSet<VARIABLES_ENTORNOS> VARIABLES_ENTORNOS { get; set; }
        public DbSet<BARRIOS_CIUDADES_VIEW> BARRIOS_CIUDADES_VIEW { get; set; }
        public DbSet<BARRIOS_VIEW> BARRIOS_VIEW { get; set; }
        public DbSet<CIUDADES_DEPARTAMENTOS_VIEW> CIUDADES_DEPARTAMENTOS_VIEW { get; set; }
        public DbSet<CIUDADES_VIEW> CIUDADES_VIEW { get; set; }
        public DbSet<COBROS_VIEW> COBROS_VIEW { get; set; }
        public DbSet<CRONOGRAMAS_CUOTAS_VIEW> CRONOGRAMAS_CUOTAS_VIEW { get; set; }
        public DbSet<DEPARTAMENTOS_PAISES_VIEW> DEPARTAMENTOS_PAISES_VIEW { get; set; }
        public DbSet<DEPARTAMENTOS_VIEW> DEPARTAMENTOS_VIEW { get; set; }
        public DbSet<EMPRESAS_VIEW> EMPRESAS_VIEW { get; set; }
        public DbSet<ENTIDADES_INMOBILIARIAS_VIEW> ENTIDADES_INMOBILIARIAS_VIEW { get; set; }
        public DbSet<FORMAS_PAGOS_VIEW> FORMAS_PAGOS_VIEW { get; set; }
        public DbSet<IMAGENES_ENTIDAD_INMOB_VIEW> IMAGENES_ENTIDAD_INMOB_VIEW { get; set; }
        public DbSet<IMAGENES_OPERACIONES_VIEW> IMAGENES_OPERACIONES_VIEW { get; set; }
        public DbSet<IMPUESTOS_VIEW> IMPUESTOS_VIEW { get; set; }
        public DbSet<INGRESOS_EGRESOS_VIEW> INGRESOS_EGRESOS_VIEW { get; set; }
        public DbSet<ITEMS_INGRESOS_EGRESOS_VIEW> ITEMS_INGRESOS_EGRESOS_VIEW { get; set; }
        public DbSet<LIQUIDACIONES_DETALLES_ITEMS> LIQUIDACIONES_DETALLES_ITEMS { get; set; }
        public DbSet<LIQUIDACIONES_VIEW> LIQUIDACIONES_VIEW { get; set; }
        public DbSet<MONEDAS_VIEW> MONEDAS_VIEW { get; set; }
        public DbSet<OPERACIONES_CONTRATOS_VENCIDOS> OPERACIONES_CONTRATOS_VENCIDOS { get; set; }
        public DbSet<OPERACIONES_PENDIENTES_VIEW> OPERACIONES_PENDIENTES_VIEW { get; set; }
        public DbSet<OPERACIONES_PROPIEDADES_VIEW> OPERACIONES_PROPIEDADES_VIEW { get; set; }
        public DbSet<PAISES_VIEW> PAISES_VIEW { get; set; }
        public DbSet<PROPIEDADES_VIEW> PROPIEDADES_VIEW { get; set; }
        public DbSet<PROPIETARIOS_ENT_INMOB_VIEW> PROPIETARIOS_ENT_INMOB_VIEW { get; set; }
        public DbSet<RESCISIONES_VIEW> RESCISIONES_VIEW { get; set; }
        public DbSet<SOCIOS_NEGOCIOS_VIEW> SOCIOS_NEGOCIOS_VIEW { get; set; }
        public DbSet<SUCURSALES_VIEW> SUCURSALES_VIEW { get; set; }
        public DbSet<USUARIOS_VIEW> USUARIOS_VIEW { get; set; }
    }
}
