//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmobiliaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERACIONES_PENDIENTES_VIEW
    {
        public long SOCIO_NEGOCIO_ID { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string NUMERO_DOCUMENTO { get; set; }
        public string RUC { get; set; }
        public long OPERACION_PROPIEDAD_ID { get; set; }
        public System.DateTime FECHA_OPERACION { get; set; }
        public long ENTIDAD_INMOBILIARIA_ID { get; set; }
        public string ENTIDAD_INMOBILIARIA { get; set; }
        public long PROPIEDAD_ID { get; set; }
        public string INMUEBLE { get; set; }
    }
}
