//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmobiliaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERACIONES_PROPIEDADES
    {
        public long OPERACION_PROPIEDAD_ID { get; set; }
        public System.DateTime FECHA_OPERACION { get; set; }
        public string TIPO_OPERACION { get; set; }
        public long SOCIO_NEGOCIO_ID { get; set; }
        public Nullable<long> PROPIEDAD_ID { get; set; }
        public Nullable<System.DateTime> FECHA_FINALIZACION { get; set; }
        public Nullable<long> ENTIDAD_INMOBILIARIA_ID { get; set; }
        public System.DateTime FECHA_INICIO_CONTRATO { get; set; }
        public Nullable<System.DateTime> FECHA_FIN_CONTRATO { get; set; }
        public Nullable<int> PLAZO { get; set; }
        public decimal PRECIO { get; set; }
        public string ESTADO { get; set; }
        public decimal GARANTIA { get; set; }
        public long SUCURSAL_ID { get; set; }
        public long MONEDA_ID { get; set; }
        public string TIPO_ENTIDAD { get; set; }
        public string TIPO_CONTRATO { get; set; }
        public string CONDICION_OPERACION { get; set; }
        public string AVISO_RENOVACION { get; set; }
        public Nullable<System.DateTime> FECHA_RENOVACION { get; set; }
        public Nullable<long> DIA_PAGO { get; set; }
        public decimal MONTO_MORA { get; set; }
        public Nullable<long> DIAS_GRACIA { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public decimal MONTO_TOTAL_OPERACION { get; set; }
        public string MONTO_TOTAL_LETRAS { get; set; }
        public Nullable<long> VENDEDOR_ID { get; set; }
        public string TIPO_FINANCIACION { get; set; }
    }
}
