//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmobiliaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERACIONES_CONTRATOS_VENCIDOS
    {
        public long OPERACION_PROPIEDAD_ID { get; set; }
        public System.DateTime FECHA_OPERACION { get; set; }
        public System.DateTime FECHA_INICIO_CONTRATO { get; set; }
        public Nullable<System.DateTime> FECHA_FIN_CONTRATO { get; set; }
        public string ESTADO { get; set; }
        public long ENTIDAD_INMOBILIARIA_ID { get; set; }
        public string UNIDAD_NEGOCIO { get; set; }
        public long PROPIEDAD_ID { get; set; }
        public string INMUEBLE { get; set; }
        public long LOCATARIO { get; set; }
        public string RAZON_SOCIAL { get; set; }
    }
}
