//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmobiliaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAISES
    {
        public PAISES()
        {
            this.DEPARTAMENTOS_PAISES = new HashSet<DEPARTAMENTOS_PAISES>();
            this.ENTIDADES_INMOBILIARIAS = new HashSet<ENTIDADES_INMOBILIARIAS>();
            this.PROPIEDADES = new HashSet<PROPIEDADES>();
        }
    
        public long PAIS_ID { get; set; }
        public string PAIS { get; set; }
        public string CODIGO_ISO_2 { get; set; }
        public string CODIGO_ISO_3 { get; set; }
        public string NACIONALIDAD { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    
        public virtual ICollection<DEPARTAMENTOS_PAISES> DEPARTAMENTOS_PAISES { get; set; }
        public virtual ICollection<ENTIDADES_INMOBILIARIAS> ENTIDADES_INMOBILIARIAS { get; set; }
        public virtual ICollection<PROPIEDADES> PROPIEDADES { get; set; }
    }
}
