//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmobiliaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPIETARIOS_ENT_INMOB_VIEW
    {
        public long PROPIETARIO_ENT_INMOB_ID { get; set; }
        public Nullable<long> ENTIDAD_INMOBILIARIA_ID { get; set; }
        public string ENTIDAD_INMOBILIARIA { get; set; }
        public Nullable<long> PROPIEDAD_ID { get; set; }
        public string PROPIEDAD { get; set; }
        public long PROPIETARIO_ID { get; set; }
        public string PROPIETARIO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
