//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmobiliaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUCURSALES
    {
        public long SUCURSAL_ID { get; set; }
        public string SUCURSAL { get; set; }
        public long EMPRESA_ID { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string POR_DEFECTO { get; set; }
    
        public virtual EMPRESAS EMPRESAS { get; set; }
    }
}
