//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmobiliaria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public string CODIGO_USUARIO { get; set; }
        public string PASSWORD { get; set; }
        public string ACTIVO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public long EMPRESA_ID { get; set; }
        public string PERFIL { get; set; }
    
        public virtual EMPRESAS EMPRESAS { get; set; }
    }
}
